### PR TITLE
Adding clang-14 coroutines support

### PR DESCRIPTION
**Pull request by ramblehead**
In clang-14 ```<experimental/coroutine>``` is replaced by ```<coroutine>```, thus need to add an additional clang version test macro to set ```BOOST_ASIO_HAS_CO_AWAIT``` correctly.

### CODE REVIEW

**Comment by raldone01** [comment]
You should consider updating your fork and force pushing to only merge 1 commit not 186.

**Comment by ramblehead** [comment]
@raldone01 I am not sure why GH shows such history from 15 years ago in this pull request. I have not seen anything like this before. The following screenshot shows how it looks in my git repo (emacs magit):

Screenshot from 2022-10-15 22-56-50

Unless I do not understand something, my Subj. commit "sits" right on top of the ```upstream/master``` branch on ```boost-1.80.0``` release tag (```upstream == "git@github.com:boostorg/asio.git"```).

I suspect, it might be a GH RP web interface bug due to complex merge history. This is how repo history looks in magit when scrolled a little down:
Screenshot from 2022-10-15 23-04-34

Let me know if you have a better idea of why it is happening.

**Comment by ramblehead** [comment]
I just realised after writing the above comment that I am trying to create PR from branch that is based on "master" into "develop" branch...

I will try to create another PR that is based on "develop" branch...

**Comment by ramblehead** [comment]
I created another PR by cherry-picking Subj. commit onto "develop" branch. The history looks clean now: #398

Closing this PR - use #398 instead...

**Pull request closed without merging**
